(()=>{
  const ROOT=document.documentElement.dataset.root||'.';
  const PAGE=document.body?.dataset.page||'home';
  const AUDIENCE=document.body?.dataset.audience||'';
  const path=p=>ROOT==='.'?`./${p}`:`${ROOT.replace(/\/$/,'')}/${p}`;
  const lang=()=>localStorage.getItem('resume-lang')||((navigator.language||'en').toLowerCase().startsWith('pl')?'pl':(navigator.language||'en').toLowerCase().startsWith('ru')?'ru':(navigator.language||'en').toLowerCase().startsWith('uk')?'uk':'en');
  const L={
    en:{facts:['Years','People','Languages'],metrics:['YEARS / TECHNOLOGY & OPERATIONS','PEOPLE / MANAGED TEAMS','NORVEXA DIRECTIONS','FEATURED PRODUCTS'],homeTitle:'Clear products. Different domains.',all:'ALL',explore:'EXPLORE →',division:{software:'Android, Windows and web products built around useful workflows.',games:'Games built around progression, systems and atmosphere.',media:'Content operations, publishing systems and automation.',labs:'Android internals, device R&D and experimental engineering.'},status:{'Active development':'Active development','Public':'Public','Concept / prototype':'Concept / prototype','Development':'Development','Hardware test build':'Hardware test build'},now:{ClearUp:['Android privacy-first system utility','ACTIVE DEVELOPMENT'],'Norvexa Reader':['Reader and document product direction','PRODUCT DEVELOPMENT'],'Luma Bay':['Mobile restoration game concept','CONCEPT / PROTOTYPE'],'BrylTab / Android R&D':['Android 16, SystemUI, Rockchip and device experiments','HARDWARE LAB']},audience:{recruiter:{title:'Kostiantyn Bryl',subtitle:'Product · Operations · Technology',lead:'10+ years across technology and operations, teams up to 20 people, plus hands-on product and software building.',links:['Experience','Selected work','Download CV']},engineering:{title:'Software builder with systems thinking.',subtitle:'Engineering / Android / Automation',lead:'Hands-on work across Android, Windows tooling, APIs, automation, Linux and device-level R&D — grounded in operational reality.',links:['Projects','Case studies','GitHub']},product:{title:'Product judgement backed by operations.',subtitle:'Product & Operations',lead:'Experience leading operations and teams, translating constraints into products, workflows and automation that people can actually use.',links:['Experience','Case studies','About']}},cv:'Download CV',cvText:'Ready PDF files optimized for recruiters and ATS. Print portfolio remains available separately.',print:'Print portfolio'},
    pl:{facts:['Lata','Osoby','Języki'],metrics:['LATA / TECHNOLOGIA I OPERACJE','OSÓB / ZARZĄDZANE ZESPOŁY','KIERUNKI NORVEXA','WYBRANE PRODUKTY'],homeTitle:'Jasne produkty. Różne domeny.',all:'WSZYSTKIE',explore:'OTWÓRZ →',division:{software:'Produkty Android, Windows i web budowane wokół użytecznych workflow.',games:'Gry oparte na progresji, systemach i atmosferze.',media:'Operacje contentowe, systemy publikacji i automatyzacja.',labs:'Android internals, R&D urządzeń i eksperymentalna inżynieria.'},status:{'Active development':'Aktywny rozwój','Public':'Publiczny','Concept / prototype':'Koncepcja / prototyp','Development':'W trakcie rozwoju','Hardware test build':'Build testowy sprzętu'},now:{ClearUp:['Privacy-first narzędzie systemowe Android','AKTYWNY ROZWÓJ'],'Norvexa Reader':['Kierunek produktu do czytania i dokumentów','ROZWÓJ PRODUKTU'],'Luma Bay':['Mobilna koncepcja gry restoration','KONCEPCJA / PROTOTYP'],'BrylTab / Android R&D':['Android 16, SystemUI, Rockchip i eksperymenty urządzeń','HARDWARE LAB']},audience:{recruiter:{title:'Kostiantyn Bryl',subtitle:'Produkt · Operacje · Technologia',lead:'Ponad 10 lat w technologii i operacjach, zespoły do 20 osób oraz praktyczne tworzenie produktów i oprogramowania.',links:['Doświadczenie','Wybrane projekty','Pobierz CV']},engineering:{title:'Software builder z myśleniem systemowym.',subtitle:'Engineering / Android / Automation',lead:'Praktyczna praca z Androidem, narzędziami Windows, API, automatyzacją, Linuxem i R&D urządzeń — osadzona w realnych procesach operacyjnych.',links:['Projekty','Case studies','GitHub']},product:{title:'Decyzje produktowe wsparte doświadczeniem operacyjnym.',subtitle:'Produkt & Operacje',lead:'Doświadczenie w prowadzeniu operacji i zespołów oraz przekładaniu ograniczeń na produkty, workflow i automatyzację.',links:['Doświadczenie','Case studies','O mnie']}},cv:'Pobierz CV',cvText:'Gotowe pliki PDF zoptymalizowane dla rekruterów i ATS. Druk portfolio pozostaje osobną opcją.',print:'Drukuj portfolio'},
    ru:{facts:['Лет','Человек','Языка'],metrics:['ЛЕТ / ТЕХНОЛОГИИ И ОПЕРАЦИИ','ЧЕЛОВЕК / УПРАВЛЯЕМЫЕ КОМАНДЫ','НАПРАВЛЕНИЯ NORVEXA','ИЗБРАННЫЕ ПРОДУКТЫ'],homeTitle:'Понятные продукты. Разные направления.',all:'ВСЕ',explore:'ОТКРЫТЬ →',division:{software:'Android, Windows и web-продукты вокруг полезных рабочих процессов.',games:'Игры вокруг прогрессии, систем и атмосферы.',media:'Контент-операции, системы публикаций и автоматизация.',labs:'Android internals, R&D устройств и экспериментальная инженерия.'},status:{'Active development':'Активная разработка','Public':'Публичный','Concept / prototype':'Концепт / прототип','Development':'В разработке','Hardware test build':'Тестовая hardware-сборка'},now:{ClearUp:['Privacy-first системная Android-утилита','АКТИВНАЯ РАЗРАБОТКА'],'Norvexa Reader':['Продуктовое направление для чтения и документов','РАЗРАБОТКА ПРОДУКТА'],'Luma Bay':['Мобильный концепт restoration-game','КОНЦЕПТ / ПРОТОТИП'],'BrylTab / Android R&D':['Android 16, SystemUI, Rockchip и эксперименты с устройствами','HARDWARE LAB']},audience:{recruiter:{title:'Kostiantyn Bryl',subtitle:'Продукт · Операции · Технологии',lead:'Более 10 лет в технологиях и операциях, управление командами до 20 человек и практическая разработка продуктов и ПО.',links:['Опыт','Избранные проекты','Скачать CV']},engineering:{title:'Разработчик с системным мышлением.',subtitle:'Engineering / Android / Automation',lead:'Практическая работа с Android, Windows tooling, API, автоматизацией, Linux и device-level R&D — с пониманием реальных операционных процессов.',links:['Проекты','Кейсы','GitHub']},product:{title:'Продуктовое мышление, подкреплённое операционным опытом.',subtitle:'Продукт & Операции',lead:'Опыт управления операциями и командами, превращения ограничений в продукты, рабочие процессы и автоматизацию.',links:['Опыт','Кейсы','Обо мне']}},cv:'Скачать CV',cvText:'Готовые PDF-файлы для рекрутеров и ATS. Печать портфолио остаётся отдельной функцией.',print:'Печать портфолио'},
    uk:{facts:['Років','Людей','Мови'],metrics:['РОКІВ / ТЕХНОЛОГІЇ ТА ОПЕРАЦІЇ','ЛЮДЕЙ / КЕРОВАНІ КОМАНДИ','НАПРЯМИ NORVEXA','ВИБРАНІ ПРОДУКТИ'],homeTitle:'Зрозумілі продукти. Різні напрями.',all:'УСІ',explore:'ВІДКРИТИ →',division:{software:'Android, Windows і web-продукти навколо корисних робочих процесів.',games:'Ігри навколо прогресії, систем та атмосфери.',media:'Контент-операції, системи публікацій та автоматизація.',labs:'Android internals, R&D пристроїв та експериментальна інженерія.'},status:{'Active development':'Активна розробка','Public':'Публічний','Concept / prototype':'Концепт / прототип','Development':'У розробці','Hardware test build':'Тестова hardware-збірка'},now:{ClearUp:['Privacy-first системна Android-утиліта','АКТИВНА РОЗРОБКА'],'Norvexa Reader':['Продуктовий напрям для читання та документів','РОЗРОБКА ПРОДУКТУ'],'Luma Bay':['Мобільний концепт restoration-game','КОНЦЕПТ / ПРОТОТИП'],'BrylTab / Android R&D':['Android 16, SystemUI, Rockchip та експерименти з пристроями','HARDWARE LAB']},audience:{recruiter:{title:'Kostiantyn Bryl',subtitle:'Продукт · Операції · Технології',lead:'Понад 10 років у технологіях та операціях, керування командами до 20 людей і практична розробка продуктів та ПЗ.',links:['Досвід','Вибрані проєкти','Завантажити CV']},engineering:{title:'Розробник із системним мисленням.',subtitle:'Engineering / Android / Automation',lead:'Практична робота з Android, Windows tooling, API, автоматизацією, Linux та device-level R&D — з розумінням реальних операційних процесів.',links:['Проєкти','Кейси','GitHub']},product:{title:'Продуктове мислення, підкріплене операційним досвідом.',subtitle:'Продукт & Операції',lead:'Досвід керування операціями й командами та перетворення обмежень на продукти, робочі процеси й автоматизацію.',links:['Досвід','Кейси','Про мене']}},cv:'Завантажити CV',cvText:'Готові PDF-файли для рекрутерів та ATS. Друк портфоліо залишається окремою функцією.',print:'Друк портфоліо'}
  };
  const locale=()=>L[lang()]||L.en;
  const setText=(el,text)=>{if(el&&typeof text==='string'&&el.textContent!==text)el.textContent=text};
  function patchHome(){if(PAGE!=='home')return;const l=locale();document.querySelectorAll('.mp-id-facts span').forEach((e,i)=>setText(e,l.facts[i]));document.querySelectorAll('.mp-metric span').forEach((e,i)=>setText(e,l.metrics[i]));setText(document.querySelector('.mp-section-head h2'),l.homeTitle)}
  function patchWork(){if(PAGE!=='work')return;const l=locale();const cards=document.querySelectorAll('.mp-division-showcase button');['software','games','media','labs'].forEach((k,i)=>{const c=cards[i];if(!c)return;setText(c.querySelector('p'),l.division[k]);setText(c.querySelector('b'),l.explore)});const all=document.querySelector('[data-division="all"]');setText(all,l.all)}
  function patchStatuses(){const l=locale();document.querySelectorAll('.mp-project-top>span').forEach(e=>{const original=e.dataset.original||e.textContent.trim();if(!e.dataset.original)e.dataset.original=original;setText(e,l.status[original]||original)});document.querySelectorAll('.mp-detail-grid article').forEach(a=>{const label=a.querySelector('small'),value=a.querySelector('h3');if(!label||!value)return;if(/status|статус/i.test(label.textContent)){const original=value.dataset.original||value.textContent.trim();if(!value.dataset.original)value.dataset.original=original;setText(value,l.status[original]||original)}})}
  function patchNow(){if(PAGE!=='now')return;const l=locale();document.querySelectorAll('.mp-now-grid article').forEach(a=>{const name=a.querySelector('h3')?.textContent.trim(),data=l.now[name];if(!data)return;setText(a.querySelector('p'),data[0]);setText(a.querySelector('b'),data[1])})}
  function patchAudience(){if(PAGE!=='audience')return;const d=locale().audience[AUDIENCE];if(!d)return;const box=document.getElementById('audienceHero');if(!box)return;setText(box.querySelector('h1'),d.title);setText(box.querySelector('strong'),d.subtitle);setText(box.querySelector('p:not(.mp-eyebrow)'),d.lead);box.querySelectorAll('.mp-audience-links>*').forEach((e,i)=>{const arrow=e.tagName==='A'?' →':'';setText(e,(d.links[i]||e.textContent.replace(/\s*→$/,''))+arrow)})}
  function patchCv(){const modal=document.getElementById('cvModal');if(!modal)return;const l=locale();setText(modal.querySelector('h2'),l.cv);const intro=modal.querySelector('form>p:not(.mp-eyebrow)');setText(intro,l.cvText);const box=modal.querySelector('.mp-cv-options');if(!box||box.dataset.final==='1')return;box.dataset.final='1';box.innerHTML=`<a href="${path('assets/cv/Kostiantyn_Bryl_CV_EN.pdf')}" download>English · PDF</a><a href="${path('assets/cv/Kostiantyn_Bryl_CV_PL.pdf')}" download>Polski · PDF</a><a href="${path('assets/cv/Kostiantyn_Bryl_CV_UA.pdf')}" download>Українська · PDF</a><a href="${path('assets/cv/Kostiantyn_Bryl_CV_RU.pdf')}" download>Русский · PDF</a><button type="button" data-final-print>${l.print}</button>`;box.querySelector('[data-final-print]').onclick=()=>window.print()}
  function injectStyle(){if(document.getElementById('final-v1-style'))return;const s=document.createElement('style');s.id='final-v1-style';s.textContent=`.mp-cv-options a{min-height:48px;border:1px solid var(--line);border-radius:12px;background:var(--surface);color:var(--text);font-size:10px;font-weight:700;display:grid;place-items:center;text-align:center;padding:8px}.mp-cv-options a:hover{border-color:var(--line2);background:var(--surface2)}.mp-cv-options [data-final-print]{grid-column:span 2;background:var(--text);color:var(--bg)}@media (max-width:1080px){.mp-identity{margin-top:80px}}`;document.head.appendChild(s)}
  function apply(){injectStyle();patchHome();patchWork();patchStatuses();patchNow();patchAudience();patchCv()}
  let timer=0;const schedule=()=>{clearTimeout(timer);timer=setTimeout(apply,20)};
  new MutationObserver(schedule).observe(document.body,{subtree:true,childList:true});
  document.addEventListener('click',e=>{if(e.target.closest('[data-lang]')||e.target.closest('[data-open-cv],#homeCv'))setTimeout(apply,30)},true);
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(apply,80)):setTimeout(apply,80);
})();
