(()=>{
const D=window.PORTFOLIO_DATA,V=window.NORVEXA_V12;if(!D||!V)return;
const ROOT=document.documentElement.dataset.root||'.',PAGE=document.body.dataset.page||'home',PROJECT=document.body.dataset.project||'',AUDIENCE=document.body.dataset.audience||'';
const path=p=>ROOT==='.'?`./${p}`:`${ROOT.replace(/\/$/,'')}/${p}`;
const lang=()=>document.documentElement.lang==='uk'?'uk':(['pl','ru'].includes(document.documentElement.lang)?document.documentElement.lang:'en');
const T=()=>V.copy[lang()]||V.copy.en,local=o=>typeof o==='string'?o:(o?.[lang()]||o?.en||''),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let snapshotCache=null,snapshotPromise=null;
function style(){if(document.getElementById('v12css'))return;const l=document.createElement('link');l.id='v12css';l.rel='stylesheet';l.href=path('proof-v12.css');document.head.appendChild(l)}
function metrics(arr){return `<div class="v12-metric-grid">${arr.map(x=>`<div class="v12-metric"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</div>`}
function header(title,lead,code='V1.2 / PROOF'){return `<div class="v12-head"><small>${code}</small><h2>${esc(title)}</h2>${lead?`<p>${esc(lead)}</p>`:''}</div>`}
function whatIDo(){if(PAGE!=='home')return;let s=document.getElementById('v12What');if(!s){s=document.createElement('section');s.id='v12What';s.className='shell v12-section';document.querySelector('.mp-metrics')?.insertAdjacentElement('afterend',s)}const t=T();s.innerHTML=header(t.what,'','PROFILE / 04')+`<div class="v12-pillars">${t.pillars.map((x,i)=>`<article class="v12-pillar"><small>0${i+1}</small><b>${esc(x)}</b></article>`).join('')}</div>`}
function featured(){if(PAGE!=='home')return;let s=document.getElementById('v12Featured');if(!s){s=document.createElement('section');s.id='v12Featured';s.className='shell v12-section';document.querySelector('.mp-home-route')?.insertAdjacentElement('afterend',s)}const t=T(),p=V.projects.clearup;s.innerHTML=header(t.featured,t.proofLead,'FEATURED / CASE 01')+`<article class="v12-featured"><div class="v12-featured-visual"><small>NORVEXA SOFTWARE / CLEARUP</small><strong>SAFE.<br>LOCAL.<br>EXPLICIT.</strong><span class="v12-proof-badge">${esc(t.conceptVisual)}</span></div><div class="v12-featured-copy"><small class="mp-eyebrow">${esc(t.proof)}</small><h3>${esc(t.featuredTitle)}</h3><p>${esc(t.featuredLead)}</p>${metrics(p.metrics)}<div class="mp-project-links"><a class="mp-btn primary" href="${path('work/clearup/')}">${esc(D.translations[lang()]?.openProject||'Open project')} →</a><a class="mp-btn" href="${p.repo}" target="_blank" rel="noreferrer">${esc(t.openRepo)}</a></div></div></article>`}
async function snapshot(){if(snapshotCache)return snapshotCache;if(snapshotPromise)return snapshotPromise;snapshotPromise=fetch(path('data/github.json'),{cache:'no-cache'}).then(r=>r.ok?r.json():null).catch(()=>null).then(x=>{snapshotCache=x;snapshotPromise=null;return x});return snapshotPromise}
function shippingCards(data){const repos=(data?.repos||[]).filter(r=>!['My-Resume','site','kostiantynbryl.githab.io'].includes(r.name)&&!r.archived).sort((a,b)=>String(b.pushed_at).localeCompare(String(a.pushed_at))).slice(0,4);return repos.map(r=>`<a class="v12-ship" href="${esc(r.html_url)}" target="_blank" rel="noreferrer"><small>${esc((r.language||'PROJECT').toUpperCase())}</small><h3>${esc(r.name)}</h3><p>${esc(r.latest_commit?.message||r.description||'Public repository activity')}</p><footer><span>${esc(String(r.pushed_at||r.updated_at||'').slice(0,10))}</span><span>${r.latest_release?esc(r.latest_release.tag_name):'GIT →'}</span></footer></a>`).join('')}
async function shipping(){if(!['home','work','now'].includes(PAGE))return;let s=document.getElementById('v12Shipping');if(!s){s=document.createElement('section');s.id='v12Shipping';s.className='shell v12-section';document.getElementById('main')?.appendChild(s)}const t=T();s.innerHTML=header(t.shipping,t.shippingLead,'BUILD / LOCAL SNAPSHOT')+`<div class="v12-shipping">${snapshotCache?shippingCards(snapshotCache):'<article class="v12-ship"><small>LOCAL SNAPSHOT</small><h3>Loading…</h3></article>'}</div>`;if(snapshotCache)return;const data=await snapshot();if(data&&document.getElementById('v12Shipping'))document.querySelector('#v12Shipping .v12-shipping').innerHTML=shippingCards(data)}
function decorateCards(){document.querySelectorAll('.mp-project-card').forEach(card=>{const name=card.querySelector('h3')?.textContent.trim(),p=D.projects.find(x=>x.name===name);if(!p)return;const proof=V.projects[p.id];if(!proof)return;let badge=card.querySelector('.v12-proof-badge');if(!badge){badge=document.createElement('span');badge.className='v12-proof-badge '+(proof.visual==='real'?'real':'');card.querySelector('.mp-project-body')?.appendChild(badge)}badge.textContent=proof.visual==='real'?T().realShot:T().conceptVisual;const img=card.querySelector('.mp-project-visual img');if(proof.shot&&img){img.src=path(proof.shot);img.loading='lazy'}})}
function workPolicy(){if(PAGE!=='work')return;let s=document.getElementById('v12WorkPolicy');if(!s){s=document.createElement('aside');s.id='v12WorkPolicy';s.className='v12-work-policy';const filters=document.getElementById('divisionFilters');filters?.insertAdjacentElement('afterend',s)}s.innerHTML=`<b>${esc(T().visualPolicy)}</b><span>${esc(T().visualPolicyText)}</span>`}
function projectProof(){if(PAGE!=='project'||!PROJECT)return;const p=V.projects[PROJECT];if(!p)return;let s=document.getElementById('v12ProjectProof');if(!s){s=document.createElement('section');s.id='v12ProjectProof';s.className='shell v12-section';const anchor=document.getElementById('v11ProjectDeep')||document.getElementById('projectDetail');anchor?.insertAdjacentElement('afterend',s)}const t=T();s.innerHTML=header(t.proof,t.proofLead,'CASE / EVIDENCE')+metrics(p.metrics)+`<div class="v12-proof-grid"><article class="v12-proof-card"><small>${esc(t.problem.toUpperCase())}</small><h3>${esc(t.problem)}</h3><p>${esc(local(p.problem))}</p></article><article class="v12-proof-card"><small>${esc(t.myRole.toUpperCase())}</small><h3>${esc(p.role)}</h3><p>${esc(local(p.built))}</p></article><article class="v12-proof-card"><small>${esc(t.built.toUpperCase())}</small><h3>${esc(t.stack)}</h3><p>${esc(p.stack)}</p></article><article class="v12-proof-card"><small>${esc(t.result.toUpperCase())}</small><h3>${esc(t.result)}</h3><p>${esc(local(p.result))}</p></article><article class="v12-proof-card wide"><small>${esc(t.evidence.toUpperCase())}</small><h3>${esc(t.visualPolicy)}</h3><p>${esc(t.visualPolicyText)}</p><div class="v12-proof-source">${p.repo?`<a href="${p.repo}" target="_blank" rel="noreferrer">GitHub README ↗</a>`:''}<span>${p.visual==='real'?esc(t.realShot):esc(t.conceptVisual)}</span></div>${p.shot?`<figure class="v12-shot"><img src="${path(p.shot)}" alt="${esc(PROJECT)} real product screenshot" loading="lazy"><figcaption><span>${esc(t.realShot)}</span><span>${esc(t.source)}: GitHub repository</span></figcaption></figure>`:`<div class="v12-visual-policy">${esc(t.visualPolicyText)}</div>`}</article></div>`}
function caseStudies(){if(PAGE!=='cases')return;document.querySelectorAll('.mp-case').forEach(card=>{const href=card.querySelector('a[href*="work/"]')?.getAttribute('href')||'',match=href.match(/work\/([^/]+)\/?/),id=match?.[1],p=id&&V.projects[id];if(!p)return;let ex=card.querySelector('.v12-case-extra');if(!ex){ex=document.createElement('div');ex.className='v12-case-extra';card.querySelector('span')?.insertAdjacentElement('beforebegin',ex)}ex.innerHTML=`<div><b>${esc(T().myRole)}</b><p>${esc(p.role)}</p></div><div><b>${esc(T().built)}</b><p>${esc(local(p.built))}</p></div><div><b>${esc(T().evidence)}</b><p>${esc(p.metrics.slice(0,2).map(x=>x.join(' ')).join(' · '))}</p></div>`})}
function experience(){if(PAGE!=='experience')return;const box=document.getElementById('experienceTimeline');if(!box)return;let summary=document.getElementById('v12Career');if(!summary){summary=document.createElement('section');summary.id='v12Career';summary.className='v12-career-summary';box.insertAdjacentElement('beforebegin',summary)}summary.innerHTML=`<div><b>10+</b><span>${esc(T().careerLead)}</span></div><div><b>20</b><span>${esc(T().scope)} / TEAM LEADERSHIP</span></div><div><b>4</b><span>TELECOM · OPERATIONS · RETAIL · BUSINESS</span></div>`;box.querySelectorAll('.mp-timeline-row').forEach(row=>{const company=row.querySelector('h3')?.textContent.trim(),d=V.experience[company];if(!d)return;let proof=row.querySelector('.v12-exp-proof');if(!proof){proof=document.createElement('div');proof.className='v12-exp-proof';row.querySelector('div')?.appendChild(proof)}proof.innerHTML=`<div><b>${esc(T().scope.toUpperCase())}</b><span>${esc(local(d.scope))}</span></div><div><b>${esc(T().impact.toUpperCase())}</b><span>${esc(local(d.impact))}</span></div>`})}
function roleProof(){if(PAGE!=='audience'||!AUDIENCE)return;const points=V.roles[AUDIENCE]?.[lang()]||V.roles[AUDIENCE]?.en;if(!points)return;const host=document.getElementById('v11Role')||document.getElementById('audienceHero');if(!host)return;let s=document.getElementById('v12RoleValue');if(!s){s=document.createElement('section');s.id='v12RoleValue';s.className='v12-role-value';host.appendChild(s)}s.innerHTML=`<h3>${esc(T().roleValue)}</h3><ul>${points.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`}
function infrastructure(){if(PAGE!=='about')return;let s=document.getElementById('v12Infra');if(!s){s=document.createElement('section');s.id='v12Infra';s.className='shell v12-section';document.getElementById('main')?.appendChild(s)}const t=T();s.innerHTML=header('Portfolio infrastructure','Conversion without unnecessary tracking.','SYSTEM / DELIVERY')+`<div class="v12-infra"><article><small>DOMAIN</small><h3>${esc(t.domainReady)}</h3><p>${esc(t.domainText)}</p></article><article><small>PRIVACY</small><h3>${esc(t.analytics)}</h3><p>${esc(t.analyticsText)}</p></article></div>`}
function dock(){let d=document.getElementById('v12Dock');if(!d){d=document.createElement('div');d.id='v12Dock';d.className='v12-recruiter-dock';document.body.appendChild(d)}const code={en:'EN',pl:'PL',ru:'RU',uk:'UA'}[lang()]||'EN',role={recruiter:'RECRUITER',engineering:'ENGINEERING',product:'PRODUCT'}[AUDIENCE],pdf=role?path(`assets/cv/Kostiantyn_Bryl_CV_${role}_${code}.pdf`):path(`assets/cv/Kostiantyn_Bryl_CV_${code}.pdf`);d.innerHTML=`<a class="primary" href="${pdf}" download>CV ↓</a><a href="https://t.me/kostiantynbryl" target="_blank" rel="noreferrer">Telegram</a><a href="mailto:kostiantynbryl@gmail.com">Email</a>`}
function recommendations(){if(!V.references?.length)return;let s=document.getElementById('v12References');if(!s){s=document.createElement('section');s.id='v12References';s.className='shell v12-section';document.getElementById('main')?.appendChild(s)}s.innerHTML=header(T().references,'','REFERENCES / VERIFIED')+`<div class="v12-proof-grid">${V.references.map(r=>`<article class="v12-proof-card"><h3>${esc(r.name)}</h3><p>${esc(local(r.text))}</p><div class="v12-proof-source"><span>${esc(r.role)}</span></div></article>`).join('')}</div>`}
function ecosystem(){if(PAGE!=='ecosystem')return;const states=['ACTIVE / SHIPPING','CONCEPT / PROTOTYPE','PRODUCT DEVELOPMENT','R&D / HARDWARE'];document.querySelectorAll('.v11-division').forEach((card,i)=>{let badge=card.querySelector('.v12-proof-badge');if(!badge){badge=document.createElement('span');badge.className='v12-proof-badge';card.appendChild(badge)}badge.textContent='EVIDENCE-FIRST / V1.2';let status=card.querySelector('.v12-ecosystem-status');if(!status){status=document.createElement('div');status.className='v12-ecosystem-status';card.appendChild(status)}status.innerHTML=`<span>STATUS</span><b>${states[i]||'ACTIVE'}</b>`})}
function apply(){style();whatIDo();featured();decorateCards();workPolicy();projectProof();caseStudies();experience();roleProof();infrastructure();dock();recommendations();ecosystem();shipping()}
let queued=false;const schedule=()=>{if(queued)return;queued=true;setTimeout(()=>{queued=false;apply()},100)};
new MutationObserver(schedule).observe(document.body,{subtree:true,childList:true});
document.addEventListener('click',e=>{if(e.target.closest('[data-lang]'))setTimeout(apply,180)},true);
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',()=>setTimeout(apply,250)):setTimeout(apply,250);
})();
