from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics

OUT=Path('assets/cv'); OUT.mkdir(parents=True,exist_ok=True)
pdfmetrics.registerFont(TTFont('Noto','/usr/share/fonts/truetype/noto/NotoSans-Regular.ttf'))
pdfmetrics.registerFont(TTFont('NotoB','/usr/share/fonts/truetype/noto/NotoSans-Bold.ttf'))
ACCENT=colors.HexColor('#1A7387'); TEXT=colors.HexColor('#17191d'); MUTED=colors.HexColor('#616873'); LINE=colors.HexColor('#d9dde2'); BG=colors.HexColor('#f6f8f9')
TOOLS='Kotlin · Android · Jetpack Compose · Python · PySide6 · FFmpeg · JavaScript · TypeScript · Next.js · NestJS · REST APIs · Git · GitHub · Linux/WSL · Magisk · LSPosed · Shizuku · Excel · Power Query · Power BI · SAP S/4HANA · Salesforce · HubSpot · MikroTik · Wireshark · Figma · OpenAI API · Make · Zapier'
COMMON_PROJECTS=[
 ('ClearUp','Android · Kotlin · Compose · Root · Shizuku'),('CutFlow Batch','Python · PySide6 · FFmpeg'),('TeleManage Enterprise','Next.js · NestJS · PostgreSQL · Redis'),('BrylTab Bouncer Glass','Android 16 · LSPosed · SystemUI · Java')]
DATA={
'en':dict(file='Kostiantyn_Bryl_CV_EN.pdf',role='Product & Operations Leader · Software Builder',summary='Product and operations leader with 10+ years across telecom, international operations, retail and entrepreneurship, combined with hands-on software development. I turn complex workflows into clear, reliable products and systems with a focus on automation, privacy and accessibility.',experience='Experience',projects='Selected Projects',skills='Core Capabilities',tools='Technology & Business Stack',languages='Languages',langs='Ukrainian · Russian · Polish · English',roles=[('2015–2018','DataGroup','Telecom Engineer','Telecommunications engineering, network diagnostics and technical operations.'),('2018–2021','TME','Head of International Orders','International order operations, process coordination and team leadership.'),('2022–2023','ALLO','Retail Manager','Retail operations, sales performance and customer-facing team management.'),('2022–Present','LLC Brillkoff','Owner','Entrepreneurship, business operations, product decisions and process ownership.')],project_desc=['Privacy-first Android storage utility with transparent scan rules and safe privileged backends.','Windows batch video trimming tool with stream-copy first and H.264/AAC fallback.','Content operations platform combining channels, scheduling, publishing, access control and billing.','Device-specific Android 16 SystemUI experiment preserving stock authentication.']),
'pl':dict(file='Kostiantyn_Bryl_CV_PL.pdf',role='Product & Operations Leader · Software Builder',summary='Lider produktu i operacji z ponad 10-letnim doświadczeniem w telekomunikacji, operacjach międzynarodowych, retailu i przedsiębiorczości, połączonym z praktycznym tworzeniem oprogramowania. Przekształcam złożone procesy w czytelne i niezawodne produkty oraz systemy.',experience='Doświadczenie',projects='Wybrane projekty',skills='Kluczowe kompetencje',tools='Technologie i systemy biznesowe',languages='Języki',langs='Ukraiński · Rosyjski · Polski · Angielski',roles=[('2015–2018','DataGroup','Inżynier telekomunikacji','Inżynieria telekomunikacyjna, diagnostyka sieci i operacje techniczne.'),('2018–2021','TME','Head of International Orders','Międzynarodowa obsługa zamówień, koordynacja procesów i zarządzanie zespołem.'),('2022–2023','ALLO','Retail Manager','Operacje retail, wyniki sprzedaży i zarządzanie zespołem obsługującym klientów.'),('2022–obecnie','LLC Brillkoff','Owner','Przedsiębiorczość, operacje biznesowe, decyzje produktowe i odpowiedzialność za procesy.')],project_desc=['Privacy-first narzędzie Android z przejrzystymi regułami skanowania i bezpiecznymi backendami Root/Shizuku.','Narzędzie Windows do seryjnego przycinania wideo ze stream-copy i fallbackiem H.264/AAC.','Platforma operacji contentowych łącząca kanały, harmonogramy, publikację, kontrolę dostępu i rozliczenia.','Eksperyment Android 16 SystemUI zachowujący stockowe uwierzytelnianie.']),
'ru':dict(file='Kostiantyn_Bryl_CV_RU.pdf',role='Product & Operations Leader · Software Builder',summary='Руководитель в области продукта и операций с опытом более 10 лет в телекоммуникациях, международных операциях, retail и предпринимательстве, совмещённым с практической разработкой ПО. Превращаю сложные процессы в понятные и надёжные продукты и системы.',experience='Опыт',projects='Избранные проекты',skills='Ключевые компетенции',tools='Технологии и бизнес-системы',languages='Языки',langs='Украинский · Русский · Польский · Английский',roles=[('2015–2018','DataGroup','Инженер телекоммуникаций','Телекоммуникационная инженерия, диагностика сетей и технические операции.'),('2018–2021','TME','Руководитель международных заказов','Международные заказы, координация процессов и руководство командой.'),('2022–2023','ALLO','Retail Manager','Retail-операции, продажи и управление командой, работающей с клиентами.'),('2022–н.в.','LLC Brillkoff','Владелец','Предпринимательство, бизнес-операции, продуктовые решения и ответственность за процессы.')],project_desc=['Privacy-first Android-утилита с прозрачными правилами сканирования и безопасными Root/Shizuku-сценариями.','Windows-инструмент пакетной обрезки видео со stream-copy и fallback H.264/AAC.','Платформа контент-операций для каналов, планирования, публикаций, контроля доступа и биллинга.','Эксперимент Android 16 SystemUI с сохранением штатной аутентификации.']),
'uk':dict(file='Kostiantyn_Bryl_CV_UA.pdf',role='Product & Operations Leader · Software Builder',summary='Керівник у сфері продукту й операцій із понад 10 роками досвіду в телекомунікаціях, міжнародних операціях, retail та підприємництві, поєднаними з практичною розробкою ПЗ. Перетворюю складні процеси на зрозумілі й надійні продукти та системи.',experience='Досвід',projects='Вибрані проєкти',skills='Ключові компетенції',tools='Технології та бізнес-системи',languages='Мови',langs='Українська · Російська · Польська · Англійська',roles=[('2015–2018','DataGroup','Інженер телекомунікацій','Телекомунікаційна інженерія, діагностика мереж і технічні операції.'),('2018–2021','TME','Керівник міжнародних замовлень','Міжнародні замовлення, координація процесів і керівництво командою.'),('2022–2023','ALLO','Retail Manager','Retail-операції, продажі та управління командою, що працює з клієнтами.'),('2022–дотепер','LLC Brillkoff','Власник','Підприємництво, бізнес-операції, продуктові рішення та відповідальність за процеси.')],project_desc=['Privacy-first Android-утиліта з прозорими правилами сканування та безпечними Root/Shizuku-сценаріями.','Windows-інструмент пакетного обрізання відео зі stream-copy та fallback H.264/AAC.','Платформа контент-операцій для каналів, планування, публікацій, контролю доступу та білінгу.','Експеримент Android 16 SystemUI зі збереженням штатної автентифікації.'])}
CAPS=['Operations & Leadership','Product Development','Process Automation','Software Development','Data & Business Systems','Networks & Technical Ops','AI / Prompt Engineering','Accessibility']

def style(name,size,leading,font='Noto',color=TEXT): return ParagraphStyle(name,fontName=font,fontSize=size,leading=leading,textColor=color)
def footer(canvas,doc):
    w,h=A4; canvas.saveState(); canvas.setStrokeColor(LINE); canvas.line(18*mm,14*mm,w-18*mm,14*mm); canvas.setFont('Noto',7); canvas.setFillColor(MUTED); canvas.drawString(18*mm,9*mm,'Kostiantyn Bryl · NORVEXA'); canvas.drawRightString(w-18*mm,9*mm,str(doc.page)); canvas.restoreState()

def build(d):
    doc=SimpleDocTemplate(str(OUT/d['file']),pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=15*mm,bottomMargin=20*mm,author='Kostiantyn Bryl',title='Kostiantyn Bryl CV')
    H1=style('h1',27,30,'NotoB'); ROLE=style('role',11,14,'NotoB',ACCENT); BODY=style('body',9,12); SMALL=style('small',7.5,10,'Noto',MUTED); SEC=style('sec',12,15,'NotoB'); CO=style('co',10,13,'NotoB'); DATE=style('date',8,10,'NotoB',ACCENT)
    s=[Paragraph('KOSTIANTYN BRYL',H1),Paragraph(d['role'],ROLE),Spacer(1,2*mm)]
    c=Table([[Paragraph('kostiantynbryl@gmail.com',SMALL),Paragraph('github.com/kostiantynbryl',SMALL),Paragraph('linkedin.com/in/kostiantyn-bryl97',SMALL)]],colWidths=[55*mm,55*mm,65*mm]); c.setStyle(TableStyle([('LEFTPADDING',(0,0),(-1,-1),0),('RIGHTPADDING',(0,0),(-1,-1),2)])); s += [c,Spacer(1,5*mm),Paragraph(d['summary'],BODY),Spacer(1,5*mm),Paragraph(d['experience'].upper(),SEC),Spacer(1,2*mm)]
    tools=['MikroTik · Wireshark · SSH/VPN','SAP · ERP · Excel','Retail · Sales · CRM','Operations · Business · Product · Automation']
    for i,(period,company,role,desc) in enumerate(d['roles']):
        t=Table([[Paragraph(period,DATE),Paragraph(company,CO)],[Paragraph('',SMALL),Paragraph(role,ROLE)],[Paragraph('',SMALL),Paragraph(desc,BODY)],[Paragraph('',SMALL),Paragraph(tools[i],SMALL)]],colWidths=[29*mm,146*mm]); t.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),0),('RIGHTPADDING',(0,0),(-1,-1),0),('BOTTOMPADDING',(0,0),(-1,-1),2),('LINEBELOW',(0,-1),(-1,-1),.4,LINE)])); s += [t,Spacer(1,2*mm)]
    s += [PageBreak(),Paragraph(d['projects'].upper(),SEC),Spacer(1,2*mm)]
    for (name,stack),desc in zip(COMMON_PROJECTS,d['project_desc']):
        t=Table([[Paragraph(name,CO)],[Paragraph(desc,BODY)],[Paragraph(stack,SMALL)]],colWidths=[175*mm]); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),BG),('BOX',(0,0),(-1,-1),.5,LINE),('LEFTPADDING',(0,0),(-1,-1),8),('RIGHTPADDING',(0,0),(-1,-1),8),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)])); s += [t,Spacer(1,2.5*mm)]
    s += [Spacer(1,2*mm),Paragraph(d['skills'].upper(),SEC),Spacer(1,2*mm)]
    rows=[[Paragraph(CAPS[i],SMALL),Paragraph(CAPS[i+1],SMALL)] for i in range(0,len(CAPS),2)]; t=Table(rows,colWidths=[87.5*mm,87.5*mm]); t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),BG),('GRID',(0,0),(-1,-1),.4,LINE),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)])); s += [t,Spacer(1,5*mm),Paragraph(d['tools'].upper(),SEC),Spacer(1,1.5*mm),Paragraph(TOOLS,SMALL),Spacer(1,5*mm),Paragraph(d['languages'].upper(),SEC),Spacer(1,1.5*mm),Paragraph(d['langs'],BODY)]
    doc.build(s,onFirstPage=footer,onLaterPages=footer)

for d in DATA.values(): build(d)
