window.NORVEXA_V3={
 divisions:{
  software:{label:'NORVEXA SOFTWARE',desc:{en:'Practical software for Android, Windows and the web.',pl:'Praktyczne oprogramowanie dla Androida, Windows i webu.',ru:'Практичное ПО для Android, Windows и web.',uk:'Практичне ПЗ для Android, Windows і web.'}},
  games:{label:'NORVEXA GAMES',desc:{en:'Games built around systems, progression and atmosphere.',pl:'Gry oparte na systemach, progresji i atmosferze.',ru:'Игры вокруг систем, прогрессии и атмосферы.',uk:'Ігри навколо систем, прогресії та атмосфери.'}},
  media:{label:'NORVEXA MEDIA',desc:{en:'Content operations, publishing systems and automation.',pl:'Operacje contentowe, publikacja i automatyzacja.',ru:'Контент-операции, публикации и автоматизация.',uk:'Контент-операції, публікації та автоматизація.'}},
  labs:{label:'NORVEXA LABS',desc:{en:'Android internals, device R&D and experimental engineering.',pl:'Android internals, R&D urządzeń i eksperymentalna inżynieria.',ru:'Android internals, R&D устройств и экспериментальная инженерия.',uk:'Android internals, R&D пристроїв та експериментальна інженерія.'}}
 },
 extra:[
  {name:'Norvexa TapSpeed',mark:'T',status:'Development',desc:'Accessibility-focused Windows productivity and assisted-input project.',stack:['Windows','Accessibility','.NET','Automation'],division:'software',private:true},
  {name:'Shadow Merge Defense',mark:'S',status:'Prototype',desc:'Portrait mobile merge-defense prototype with tower progression, waves and meta systems.',stack:['Godot','Mobile','Game Design'],division:'games',private:true},
  {name:'TeleManage Enterprise',mark:'M',status:'Development',desc:'Content operations platform for channels, scheduling, publishing, RBAC and billing.',stack:['Next.js','NestJS','PostgreSQL','Redis'],division:'media',private:true}
 ],
 map:{'ClearUp':'software','Norvexa OneStep':'software','CutFlow Batch':'software','Norvexa Reader':'software','Luma Bay':'games','BrylTab Bouncer Glass':'labs'},
 text:{
  en:{eco:'One ecosystem. Four focused directions.',lead:'Software, games, media systems and experimental R&D — separated by purpose, united by product discipline.',all:'ALL',how:'HOW I WORK',howTitle:'Understand the system. Remove friction. Build what matters.',featured:'FEATURED / NORVEXA SOFTWARE',featuredTitle:'ClearUp — privacy-first Android utility.',featuredBody:'Transparent scan rules, local processing and safe Root/Shizuku paths instead of opaque one-click cleanup.'},
  pl:{eco:'Jeden ekosystem. Cztery wyspecjalizowane kierunki.',lead:'Software, gry, systemy mediowe i eksperymentalne R&D — różne cele, wspólna dyscyplina produktowa.',all:'WSZYSTKIE',how:'JAK PRACUJĘ',howTitle:'Zrozum system. Usuń tarcie. Zbuduj to, co ma znaczenie.',featured:'GŁÓWNY / NORVEXA SOFTWARE',featuredTitle:'ClearUp — privacy-first narzędzie Android.',featuredBody:'Przejrzyste reguły skanowania, lokalne przetwarzanie i bezpieczne ścieżki Root/Shizuku.'},
  ru:{eco:'Одна экосистема. Четыре сфокусированных направления.',lead:'Software, games, media systems и экспериментальный R&D — разные задачи, единый продуктовый подход.',all:'ВСЕ',how:'КАК Я РАБОТАЮ',howTitle:'Понять систему. Убрать трение. Построить то, что важно.',featured:'КЛЮЧЕВОЙ / NORVEXA SOFTWARE',featuredTitle:'ClearUp — privacy-first Android-утилита.',featuredBody:'Прозрачные правила сканирования, локальная обработка и безопасные Root/Shizuku-сценарии.'},
  uk:{eco:'Одна екосистема. Чотири сфокусовані напрями.',lead:'Software, games, media systems та експериментальний R&D — різні задачі, єдиний продуктовий підхід.',all:'УСІ',how:'ЯК Я ПРАЦЮЮ',howTitle:'Зрозуміти систему. Прибрати тертя. Побудувати важливе.',featured:'КЛЮЧОВИЙ / NORVEXA SOFTWARE',featuredTitle:'ClearUp — privacy-first Android-утиліта.',featuredBody:'Прозорі правила сканування, локальна обробка та безпечні Root/Shizuku-сценарії.'}
 },
 principles:{
  en:[['01','Understand the system','Map the real workflow before choosing a tool.'],['02','Remove friction','Find repeated decisions, manual steps and unclear ownership.'],['03','Build the simplest reliable solution','Prefer explicit behaviour over unnecessary complexity.'],['04','Measure what matters','Use outcomes, feedback and logs to test the system.'],['05','Improve continuously','Treat the first working version as a foundation.']],
  pl:[['01','Zrozum system','Najpierw mapuj realny proces, potem wybieraj narzędzie.'],['02','Usuń tarcie','Znajdź powtarzalne decyzje, ręczne kroki i niejasną odpowiedzialność.'],['03','Buduj prosto i niezawodnie','Preferuj jawne zachowanie zamiast zbędnej złożoności.'],['04','Mierz to, co ważne','Wyniki, feedback i logi pokazują, czy system działa.'],['05','Ulepszaj stale','Pierwsza działająca wersja to fundament.']],
  ru:[['01','Понять систему','Сначала картировать реальный процесс, потом выбирать инструмент.'],['02','Убрать трение','Найти повторяющиеся решения, ручные шаги и неясную ответственность.'],['03','Строить просто и надёжно','Предпочитать явное поведение лишней сложности.'],['04','Измерять важное','Результаты, feedback и логи показывают, работает ли система.'],['05','Улучшать постоянно','Первая рабочая версия — это фундамент.']],
  uk:[['01','Зрозуміти систему','Спочатку мапувати реальний процес, потім обирати інструмент.'],['02','Прибрати тертя','Знайти повторювані рішення, ручні кроки та нечітку відповідальність.'],['03','Будувати просто й надійно','Віддавати перевагу явній поведінці зайвій складності.'],['04','Вимірювати важливе','Результати, feedback і логи показують, чи працює система.'],['05','Покращувати постійно','Перша робоча версія — це фундамент.']]
 }
};
