(()=>{
  const A=window.KB_APP,D=window.PORTFOLIO_DATA;if(!A||!D)return;
  const supported=['en','pl','ru','uk','zh'];
  const htmlLang={en:'en',pl:'pl',ru:'ru',uk:'uk',zh:'zh-CN'};
  const labels={en:'EN',pl:'PL',ru:'RU',uk:'UA',zh:'中文'};
  const clean={
    en:{brand:'PERSONAL PORTFOLIO',home:'Home',work:'Work',experience:'Experience',cases:'Case studies',about:'About',now:'Now',ecosystem:'Project ecosystem',contact:'Contact',available:'Open to selected opportunities',profile:'Product & Operations Leader · Software Builder',heroK:'Product · Operations · Technology',hero1:'I turn complex work',hero2:'into clear products and systems.',heroLead:'I combine operations, product thinking and hands-on software development — focused on useful systems, automation, privacy and accessibility.',explore:'Explore work',download:'Download CV',pageWork:'Four directions. One product discipline.',pageWorkLead:'Software, games, media systems and experimental R&D are separated by purpose so each project gets the context it needs.',pageExp:'Career across technology and operations.',pageExpLead:'From telecom engineering to international operations, retail leadership, entrepreneurship and product building.',pageCases:'Decisions made under real constraints.',pageCasesLead:'Focused case studies: problem, constraints, approach and outcome.',pageAbout:'Business judgement with a builder’s instinct.',pageAboutLead:'What I do, how I think and how I work.',pageNow:'What I am building now.',pageNowLead:'A compact view of active products and experiments.',pageContact:'A useful conversation can start with one clear problem.',pageContactLead:'Open to product, operations, automation and software opportunities with remote and EU-facing teams.',problem:'Problem',approach:'Approach',result:'Result',role:'Role',stack:'Stack',status:'Status',openProject:'Open project',backWork:'Back to work',projectOverview:'Project overview',projectGallery:'Project visuals',footer:'Updated — Aug 2026',cvTitle:'Download CV',cvText:'Choose a language and download the current CV.',printPortfolio:'Print portfolio',close:'Close',menu:'Menu',aboutDo:'What I do',aboutThink:'How I think',aboutWork:'How I work',audience:'Tailored view',all:'All',exploreShort:'Explore →'},
    pl:{brand:'PORTFOLIO OSOBISTE',home:'Start',work:'Projekty',experience:'Doświadczenie',cases:'Case studies',about:'O mnie',now:'Teraz',ecosystem:'Ekosystem projektów',contact:'Kontakt',available:'Otwarty na wybrane propozycje',profile:'Lider produktu i operacji · Twórca oprogramowania',heroK:'Produkt · Operacje · Technologia',hero1:'Zmieniam złożoną pracę',hero2:'w jasne produkty i systemy.',heroLead:'Łączę operacje, myślenie produktowe i praktyczne tworzenie oprogramowania — z naciskiem na użyteczne systemy, automatyzację, prywatność i dostępność.',explore:'Zobacz projekty',download:'Pobierz CV',pageWork:'Cztery kierunki. Jedna dyscyplina produktowa.',pageWorkLead:'Oprogramowanie, gry, systemy mediowe i eksperymentalne R&D są rozdzielone według celu, aby każdy projekt miał właściwy kontekst.',pageExp:'Kariera na styku technologii i operacji.',pageExpLead:'Od inżynierii telekomunikacyjnej przez operacje międzynarodowe i retail do przedsiębiorczości i budowania produktów.',pageCases:'Decyzje podejmowane w realnych ograniczeniach.',pageCasesLead:'Skoncentrowane case studies: problem, ograniczenia, podejście i rezultat.',pageAbout:'Osąd biznesowy z instynktem twórcy.',pageAboutLead:'Co robię, jak myślę i jak pracuję.',pageNow:'Co buduję teraz.',pageNowLead:'Krótki przegląd aktywnych produktów i eksperymentów.',pageContact:'Dobra rozmowa może zacząć się od jednego konkretnego problemu.',pageContactLead:'Jestem otwarty na role produktowe, operacyjne, automatyzacyjne i software w zespołach zdalnych i europejskich.',problem:'Problem',approach:'Podejście',result:'Rezultat',role:'Rola',stack:'Stack',status:'Status',openProject:'Otwórz projekt',backWork:'Wróć do projektów',projectOverview:'Opis projektu',projectGallery:'Materiały projektu',footer:'Aktualizacja — sie 2026',cvTitle:'Pobierz CV',cvText:'Wybierz język i pobierz aktualne CV.',printPortfolio:'Drukuj portfolio',close:'Zamknij',menu:'Menu',aboutDo:'Co robię',aboutThink:'Jak myślę',aboutWork:'Jak pracuję',audience:'Widok dopasowany',all:'Wszystkie',exploreShort:'Otwórz →'},
    ru:{brand:'ЛИЧНОЕ ПОРТФОЛИО',home:'Главная',work:'Проекты',experience:'Опыт',cases:'Кейсы',about:'Обо мне',now:'Сейчас',ecosystem:'Экосистема проектов',contact:'Контакты',available:'Открыт к интересным предложениям',profile:'Руководитель продукта и операций · Разработчик ПО',heroK:'Продукт · Операции · Технологии',hero1:'Превращаю сложную работу',hero2:'в понятные продукты и системы.',heroLead:'Объединяю операционное управление, продуктовое мышление и практическую разработку — с фокусом на полезные системы, автоматизацию, приватность и доступность.',explore:'Смотреть проекты',download:'Скачать CV',pageWork:'Четыре направления. Один продуктовый подход.',pageWorkLead:'Программные продукты, игры, медиасистемы и экспериментальные R&D-проекты разделены по назначению, чтобы каждый проект получил правильный контекст.',pageExp:'Карьера на стыке технологий и операций.',pageExpLead:'От телеком-инженерии к международным операциям, управлению розницей, предпринимательству и созданию продуктов.',pageCases:'Решения в реальных ограничениях.',pageCasesLead:'Сфокусированные кейсы: проблема, ограничения, подход и результат.',pageAbout:'Бизнес-мышление с инстинктом создателя.',pageAboutLead:'Что я делаю, как думаю и как работаю.',pageNow:'Что я создаю сейчас.',pageNowLead:'Короткий обзор активных продуктов и экспериментов.',pageContact:'Полезный разговор может начаться с одной понятной проблемы.',pageContactLead:'Открыт к предложениям в продукте, операциях, автоматизации и разработке ПО — в удалённых и ориентированных на ЕС командах.',problem:'Проблема',approach:'Подход',result:'Результат',role:'Роль',stack:'Стек',status:'Статус',openProject:'Открыть проект',backWork:'Назад к проектам',projectOverview:'О проекте',projectGallery:'Материалы проекта',footer:'Обновлено — авг 2026',cvTitle:'Скачать CV',cvText:'Выберите язык и скачайте актуальное CV.',printPortfolio:'Печать портфолио',close:'Закрыть',menu:'Меню',aboutDo:'Что я делаю',aboutThink:'Как я думаю',aboutWork:'Как я работаю',audience:'Версия под аудиторию',all:'Все',exploreShort:'Открыть →'},
    uk:{brand:'ОСОБИСТЕ ПОРТФОЛІО',home:'Головна',work:'Проєкти',experience:'Досвід',cases:'Кейси',about:'Про мене',now:'Зараз',ecosystem:'Екосистема проєктів',contact:'Контакти',available:'Відкритий до цікавих пропозицій',profile:'Керівник продукту й операцій · Розробник ПЗ',heroK:'Продукт · Операції · Технології',hero1:'Перетворюю складну роботу',hero2:'на зрозумілі продукти й системи.',heroLead:'Поєдную операційне управління, продуктове мислення та практичну розробку — з фокусом на корисні системи, автоматизацію, приватність і доступність.',explore:'Дивитися проєкти',download:'Завантажити CV',pageWork:'Чотири напрями. Один продуктовий підхід.',pageWorkLead:'Програмні продукти, ігри, медіасистеми й експериментальні R&D-проєкти розділено за призначенням, щоб кожен проєкт мав правильний контекст.',pageExp:'Кар’єра на стику технологій та операцій.',pageExpLead:'Від телеком-інженерії до міжнародних операцій, керування роздробом, підприємництва та створення продуктів.',pageCases:'Рішення в реальних обмеженнях.',pageCasesLead:'Сфокусовані кейси: проблема, обмеження, підхід і результат.',pageAbout:'Бізнес-мислення з інстинктом творця.',pageAboutLead:'Що я роблю, як думаю та як працюю.',pageNow:'Що я створюю зараз.',pageNowLead:'Короткий огляд активних продуктів та експериментів.',pageContact:'Корисна розмова може початися з однієї зрозумілої проблеми.',pageContactLead:'Відкритий до пропозицій у продукті, операціях, автоматизації та розробці ПЗ — у віддалених і орієнтованих на ЄС командах.',problem:'Проблема',approach:'Підхід',result:'Результат',role:'Роль',stack:'Стек',status:'Статус',openProject:'Відкрити проєкт',backWork:'Назад до проєктів',projectOverview:'Про проєкт',projectGallery:'Матеріали проєкту',footer:'Оновлено — сер 2026',cvTitle:'Завантажити CV',cvText:'Оберіть мову та завантажте актуальне CV.',printPortfolio:'Друк портфоліо',close:'Закрити',menu:'Меню',aboutDo:'Що я роблю',aboutThink:'Як я думаю',aboutWork:'Як я працюю',audience:'Версія під аудиторію',all:'Усі',exploreShort:'Відкрити →'},
    zh:{brand:'个人作品集',home:'首页',work:'项目',experience:'经历',cases:'案例',about:'关于我',now:'现在',ecosystem:'项目生态',contact:'联系方式',available:'开放接受合适的机会',profile:'产品与运营负责人 · 软件开发者',heroK:'产品 · 运营 · 技术',hero1:'将复杂工作转化',hero2:'为清晰的产品与系统。',heroLead:'我把运营管理、产品思维与实际软件开发结合起来，专注于实用系统、自动化、隐私与可访问性。',explore:'查看项目',download:'下载简历',pageWork:'四个方向，一套产品方法。',pageWorkLead:'软件、游戏、媒体系统与实验性研发按目标划分，让每个项目都有合适的语境。',pageExp:'跨越技术与运营的职业经历。',pageExpLead:'从电信工程、国际运营与零售管理，到创业与产品开发。',pageCases:'在真实约束下做出的决策。',pageCasesLead:'聚焦问题、限制、方法与结果的案例。',pageAbout:'商业判断与构建者思维。',pageAboutLead:'我做什么、如何思考、如何工作。',pageNow:'我现在正在构建什么。',pageNowLead:'当前产品与实验项目的简要视图。',pageContact:'一次有价值的交流，可以从一个明确的问题开始。',pageContactLead:'欢迎产品、运营、自动化与软件方向的机会，尤其是远程和面向欧洲的团队。',problem:'问题',approach:'方法',result:'结果',role:'角色',stack:'技术栈',status:'状态',openProject:'查看项目',backWork:'返回项目',projectOverview:'项目概览',projectGallery:'项目材料',footer:'更新于 2026 年 8 月',cvTitle:'下载简历',cvText:'选择语言并下载当前简历。',printPortfolio:'打印作品集',close:'关闭',menu:'菜单',aboutDo:'我做什么',aboutThink:'我如何思考',aboutWork:'我如何工作',audience:'定制视图',all:'全部',exploreShort:'查看 →'}
  };
  const extra={
    en:{footerPortfolio:'Portfolio',footerProfile:'Profile',footerLinks:'Links',email:'Email',theme:'Theme',command:'Search portfolio',pageEyebrow:{work:'PORTFOLIO / WORK',experience:'CAREER / EXPERIENCE',cases:'PRODUCT / CASE STUDIES',about:'PROFILE / ABOUT',now:'NOW / AUG 2026',contact:'CONNECT / DIRECT'},divisions:{software:['Software','Android, Windows and web products built around useful workflows.'],games:['Games','Games built around progression, systems and atmosphere.'],media:['Media','Content operations, publishing systems and automation.'],labs:['Labs','Android internals, device R&D and experimental engineering.']},aboutCopy:['I connect operations, product and technical execution, carrying work from problem framing to a usable system.','System and constraints first, tools second. I prefer explicit behavior, measurable outcomes and reversible decisions.','I remove unnecessary complexity, automate repeated steps and improve from feedback, logs and real usage.'],contactRole:'Product · Operations · Software · Automation',contactDirect:'Direct channels only. No contact-form tracking layer.',qrTitle:'Resume QR',qrText:'Scan to open the latest published version of this portfolio.',homeWhat:'What I actually do',pillars:[['Build products','From idea and structure to a working solution.'],['Lead operations','I build processes, roles and control around real work.'],['Automate systems','I remove repetitive manual steps and unnecessary friction.'],['Ship software','I move from concept to a working, testable result.']],featured:'Featured case',featuredProof:'Evidence & result',featuredTitle:'ClearUp — safety before spectacle.',featuredLead:'An Android storage utility where privileged actions are explicit, local and auditable instead of hidden behind a one-tap promise.',safe:'SAFE.\nLOCAL.\nEXPLICIT.',metrics:['privileged execution paths','fixed Shizuku operations','accessibility request timeout','ads / analytics / account / cloud'],visualNote:'Product visual — not a UI screenshot',openEvidence:'Open source evidence ↗'},
    pl:{footerPortfolio:'Portfolio',footerProfile:'Profil',footerLinks:'Linki',email:'Email',theme:'Motyw',command:'Przeszukaj portfolio',pageEyebrow:{work:'PORTFOLIO / PROJEKTY',experience:'KARIERA / DOŚWIADCZENIE',cases:'PRODUKT / CASE STUDIES',about:'PROFIL / O MNIE',now:'TERAZ / SIE 2026',contact:'KONTAKT / BEZPOŚREDNIO'},divisions:{software:['Software','Produkty Android, Windows i web budowane wokół użytecznych workflow.'],games:['Gry','Gry oparte na progresji, systemach i atmosferze.'],media:['Media','Operacje contentowe, systemy publikacji i automatyzacja.'],labs:['Labs','Android internals, R&D urządzeń i eksperymentalna inżynieria.']},aboutCopy:['Łączę operacje, produkt i wykonanie techniczne, prowadząc pracę od definicji problemu do użytecznego systemu.','Najpierw system i ograniczenia, potem narzędzia. Preferuję jawne zachowanie, mierzalne wyniki i odwracalne decyzje.','Usuwam zbędną złożoność, automatyzuję powtarzalne kroki i ulepszam rozwiązania na podstawie feedbacku, logów i realnego użycia.'],contactRole:'Produkt · Operacje · Software · Automatyzacja',contactDirect:'Tylko bezpośrednie kanały. Bez śledzącego formularza kontaktowego.',qrTitle:'QR do CV',qrText:'Zeskanuj, aby otworzyć najnowszą opublikowaną wersję portfolio.',homeWhat:'Co robię w praktyce',pillars:[['Tworzę produkty','Od pomysłu i struktury do działającego rozwiązania.'],['Prowadzę operacje','Buduję procesy, role i kontrolę wokół realnej pracy.'],['Automatyzuję systemy','Usuwam ręczną rutynę i zbędne straty czasu.'],['Dostarczam software','Prowadzę rozwiązanie od koncepcji do działającego wyniku.']],featured:'Kluczowy case',featuredProof:'Dowody i rezultat',featuredTitle:'ClearUp — bezpieczeństwo przed efektem.',featuredLead:'Narzędzie Android, w którym uprzywilejowane działania są jawne, lokalne i możliwe do audytu, zamiast ukryte za obietnicą jednego kliknięcia.',safe:'BEZPIECZNIE.\nLOKALNIE.\nJAWNIE.',metrics:['ścieżki uprzywilejowanego wykonania','stałe operacje Shizuku','timeout żądania accessibility','reklamy / analityka / konto / chmura'],visualNote:'Wizualizacja produktu — nie screenshot UI',openEvidence:'Otwórz dowody w repozytorium ↗'},
    ru:{footerPortfolio:'Портфолио',footerProfile:'Профиль',footerLinks:'Ссылки',email:'Почта',theme:'Тема',command:'Поиск по портфолио',pageEyebrow:{work:'ПОРТФОЛИО / ПРОЕКТЫ',experience:'КАРЬЕРА / ОПЫТ',cases:'ПРОДУКТ / КЕЙСЫ',about:'ПРОФИЛЬ / ОБО МНЕ',now:'СЕЙЧАС / АВГ 2026',contact:'КОНТАКТ / НАПРЯМУЮ'},divisions:{software:['ПО','Android, Windows и web-продукты вокруг полезных рабочих процессов.'],games:['Игры','Игры вокруг прогрессии, систем и атмосферы.'],media:['Медиа','Контент-операции, системы публикаций и автоматизация.'],labs:['Лаборатория','Android internals, R&D устройств и экспериментальная инженерия.']},aboutCopy:['Соединяю операции, продукт и техническую реализацию, доводя работу от формулировки проблемы до полезной системы.','Сначала система и ограничения, затем инструменты. Предпочитаю явное поведение, измеримые результаты и обратимые решения.','Убираю лишнюю сложность, автоматизирую повторяющиеся шаги и улучшаю решения по обратной связи, логам и реальному использованию.'],contactRole:'Продукт · Операции · Разработка ПО · Автоматизация',contactDirect:'Только прямые каналы связи. Без отслеживающей контактной формы.',qrTitle:'QR резюме',qrText:'Отсканируйте, чтобы открыть последнюю опубликованную версию портфолио.',homeWhat:'Чем я полезен бизнесу',pillars:[['Создаю продукты','От идеи и структуры до рабочего решения.'],['Управляю операциями','Выстраиваю процессы, роли и контроль вокруг реальной работы.'],['Автоматизирую системы','Убираю ручную рутину и лишние потери времени.'],['Довожу до результата','Не просто проектирую, а довожу до рабочего и проверяемого состояния.']],featured:'Ключевой кейс',featuredProof:'Доказательства и результат',featuredTitle:'ClearUp — безопасность важнее эффектности.',featuredLead:'Android-утилита, в которой привилегированные действия сделаны явными, локальными и проверяемыми, а не скрыты за обещанием «одной кнопки».',safe:'БЕЗОПАСНО.\nЛОКАЛЬНО.\nПРОЗРАЧНО.',metrics:['пути привилегированного выполнения','фиксированные операции Shizuku','таймаут запроса accessibility','реклама / аналитика / аккаунт / cloud'],visualNote:'Визуал продукта — не скриншот UI',openEvidence:'Открыть исходные доказательства ↗'},
    uk:{footerPortfolio:'Портфоліо',footerProfile:'Профіль',footerLinks:'Посилання',email:'Пошта',theme:'Тема',command:'Пошук у портфоліо',pageEyebrow:{work:'ПОРТФОЛІО / ПРОЄКТИ',experience:'КАР’ЄРА / ДОСВІД',cases:'ПРОДУКТ / КЕЙСИ',about:'ПРОФІЛЬ / ПРО МЕНЕ',now:'ЗАРАЗ / СЕР 2026',contact:'КОНТАКТ / НАПРЯМУ'},divisions:{software:['ПЗ','Android, Windows і web-продукти навколо корисних робочих процесів.'],games:['Ігри','Ігри навколо прогресії, систем та атмосфери.'],media:['Медіа','Контент-операції, системи публікацій та автоматизація.'],labs:['Лабораторія','Android internals, R&D пристроїв та експериментальна інженерія.']},aboutCopy:['Поєдную операції, продукт і технічну реалізацію, ведучи роботу від формулювання проблеми до корисної системи.','Спочатку система й обмеження, потім інструменти. Віддаю перевагу явній поведінці, вимірюваним результатам і зворотним рішенням.','Прибираю зайву складність, автоматизую повторювані кроки й покращую рішення за зворотним зв’язком, логами та реальним використанням.'],contactRole:'Продукт · Операції · Розробка ПЗ · Автоматизація',contactDirect:'Тільки прямі канали зв’язку. Без контактної форми з відстеженням.',qrTitle:'QR резюме',qrText:'Відскануйте, щоб відкрити останню опубліковану версію портфоліо.',homeWhat:'Чим я корисний бізнесу',pillars:[['Створюю продукти','Від ідеї та структури до робочого рішення.'],['Керую операціями','Вибудовую процеси, ролі та контроль навколо реальної роботи.'],['Автоматизую системи','Прибираю ручну рутину та зайві втрати часу.'],['Доводжу до результату','Не лише проєктую, а доводжу до робочого й перевірюваного стану.']],featured:'Ключовий кейс',featuredProof:'Докази та результат',featuredTitle:'ClearUp — безпека важливіша за ефектність.',featuredLead:'Android-утиліта, у якій привілейовані дії зроблено явними, локальними й перевірюваними, а не приховано за обіцянкою «однієї кнопки».',safe:'БЕЗПЕЧНО.\nЛОКАЛЬНО.\nПРОЗОРО.',metrics:['шляхи привілейованого виконання','фіксовані операції Shizuku','таймаут запиту accessibility','реклама / аналітика / акаунт / cloud'],visualNote:'Візуал продукту — не скриншот UI',openEvidence:'Відкрити вихідні докази ↗'},
    zh:{footerPortfolio:'作品集',footerProfile:'个人资料',footerLinks:'链接',email:'邮箱',theme:'主题',command:'搜索作品集',pageEyebrow:{work:'作品集 / 项目',experience:'职业 / 经历',cases:'产品 / 案例',about:'个人 / 关于我',now:'现在 / 2026年8月',contact:'联系 / 直接沟通'},divisions:{software:['软件','围绕实用工作流程构建的 Android、Windows 与 Web 产品。'],games:['游戏','围绕成长、系统与氛围构建的游戏。'],media:['媒体','内容运营、发布系统与自动化。'],labs:['实验室','Android 底层、设备研发与实验性工程。']},aboutCopy:['我连接运营、产品与技术执行，把工作从问题定义推进到可用系统。','我先理解系统及其约束，再选择工具；偏好明确的行为、可衡量的结果和可逆的决策。','我减少不必要的复杂度，自动化重复步骤，并依据反馈、日志与真实使用持续改进。'],contactRole:'产品 · 运营 · 软件开发 · 自动化',contactDirect:'只使用直接联系方式，不使用带追踪的联系表单。',qrTitle:'简历二维码',qrText:'扫码打开最新发布的个人作品集。',homeWhat:'我能为业务做什么',pillars:[['构建产品','从想法和结构推进到真正可用的解决方案。'],['管理运营','围绕真实工作建立流程、角色与控制。'],['自动化系统','减少重复手工步骤和不必要的时间损耗。'],['交付软件','把概念推进到可运行、可测试的结果。']],featured:'重点案例',featuredProof:'证据与结果',featuredTitle:'ClearUp — 安全优先于炫技。',featuredLead:'这是一款 Android 存储工具，高权限操作明确、本地且可审计，而不是隐藏在“一键完成”的承诺之后。',safe:'安全。\n本地。\n透明。',metrics:['高权限执行路径','固定 Shizuku 操作','Accessibility 请求超时','广告 / 分析 / 账户 / 云端'],visualNote:'产品概念视觉 — 非 UI 截图',openEvidence:'查看开源证据 ↗'}
  };
  const zhProject={
    clearup:'以隐私为先的 Android 存储工具，扫描规则透明、本地处理，并使用受控且安全的高权限执行路径。',
    'cutflow-batch':'Windows 批量视频裁剪工具，优先使用 stream-copy，必要时回退到 H.264/AAC 重新编码。',
    'luma-bay':'以成长、氛围和短时移动体验为核心的修复经营类游戏概念。',
    telemanage:'内容运营平台，将频道、排期、发布、权限控制和计费整合到统一工作模型中。',
    bryltab:'针对特定设备的 SystemUI 实验，在保留系统原生身份验证的同时，让 PIN 解锁层接近透明。',
    'norvexa-onestep':'离线优先的目标规划工具，把复杂目标拆成一个明确的下一步。',
    'norvexa-reader':'面向阅读与文档工作流的产品方向，强调清晰、专注与本地体验。',
    'shadow-merge-defense':'将合并、塔防和成长系统结合起来的移动游戏原型。',
    'norvexa-tapspeed':'围绕输入速度、无障碍与 Windows 桌面交互构建的实验性工具。'
  };
  const zhExp={DataGroup:'电信工程、网络诊断与技术运营。',TME:'国际订单运营、流程协调与团队管理。',ALLO:'零售运营、销售表现与面向客户团队的管理。','LLC Brillkoff':'创业、业务运营、产品决策与流程负责人。'};
  const status={
    en:{'Active development':'Active development','Public':'Public','Concept / prototype':'Concept / prototype','Development':'Development','Hardware test build':'Hardware test build'},
    pl:{'Active development':'Aktywny rozwój','Public':'Publiczny','Concept / prototype':'Koncepcja / prototyp','Development':'W rozwoju','Hardware test build':'Testowy build sprzętowy'},
    ru:{'Active development':'Активная разработка','Public':'Публичный','Concept / prototype':'Концепт / прототип','Development':'В разработке','Hardware test build':'Тестовая аппаратная сборка'},
    uk:{'Active development':'Активна розробка','Public':'Публічний','Concept / prototype':'Концепт / прототип','Development':'У розробці','Hardware test build':'Тестова апаратна збірка'},
    zh:{'Active development':'积极开发中','Public':'公开项目','Concept / prototype':'概念 / 原型','Development':'开发中','Hardware test build':'硬件测试版本'}
  };
  D.projects?.forEach(p=>{if(p.desc&&zhProject[p.id])p.desc.zh=zhProject[p.id]});
  D.experience?.forEach(x=>{if(x.desc&&zhExp[x.company])x.desc.zh=zhExp[x.company]});
  const getInitial=()=>{
    const q=new URLSearchParams(location.search).get('lang');
    const query=q&&q.toLowerCase().startsWith('zh')?'zh':q;
    if(supported.includes(query))return query;
    try{const legacy=localStorage.getItem('resume-lang-ext')==='zh'?'zh':localStorage.getItem('resume-lang');if(supported.includes(legacy))return legacy}catch{}
    const n=(navigator.language||'en').toLowerCase();return n.startsWith('zh')?'zh':n.startsWith('pl')?'pl':n.startsWith('ru')?'ru':n.startsWith('uk')?'uk':'en';
  };
  let current=getInitial();
  const setHtml=()=>{document.documentElement.lang=htmlLang[current];document.documentElement.dataset.locale=current};
  const save=()=>{try{localStorage.setItem('resume-lang',current);localStorage.removeItem('resume-lang-ext')}catch{}};
  const t=(key,def='')=>{
    const parts=key.split('.');let v={...clean[current],...extra[current]};for(const p of parts)v=v?.[p];return v??def;
  };
  const local=o=>typeof o==='string'?o:(o?.[current]||o?.en||'');
  const set=lang=>{lang=String(lang||'').toLowerCase().startsWith('zh')?'zh':lang;if(!supported.includes(lang)||lang===current)return;current=lang;setHtml();save();window.dispatchEvent(new CustomEvent('kb:languagechange',{detail:{lang}}))};
  const api={supported,labels,get lang(){return current},set,t,local,status:s=>status[current]?.[s]||s,dict:()=>({...clean[current],...extra[current]}),htmlLang};
  window.KB_I18N=api;setHtml();save();
})();
