(()=>{
  const A=window.KB_APP,I=window.KB_I18N,D=window.PORTFOLIO_DATA;if(!A||!I)return;
  const code=()=>({en:'EN',pl:'PL',ru:'RU',uk:'UA',zh:'ZH'}[I.lang]);
  const roleCode=()=>A.page==='audience'?({recruiter:'RECRUITER',engineering:'ENGINEERING',product:'PRODUCT'}[A.audience]||''):'';
  function themeInit(){let v='dark';try{v=localStorage.getItem('resume-theme')||document.documentElement.dataset.theme||'dark'}catch{}document.documentElement.dataset.theme=v}
  function toggleTheme(){const cur=document.documentElement.dataset.theme||'dark',next=cur==='dark'?'light':'dark';document.documentElement.dataset.theme=next;try{localStorage.setItem('resume-theme',next)}catch{}}
  function cvModal(){document.getElementById('kbCvModal')?.remove();const d=document.createElement('dialog');d.className='mp-modal';d.id='kbCvModal';const current=code(),role=roleCode();const files=I.supported.map(l=>{const c={en:'EN',pl:'PL',ru:'RU',uk:'UA',zh:'ZH'}[l],label={en:'English',pl:'Polski',ru:'Русский',uk:'Українська',zh:'简体中文'}[l],name=role?`Kostiantyn_Bryl_CV_${role}_${c}.pdf`:`Kostiantyn_Bryl_CV_${c}.pdf`;return`<a class="kb-cv-link ${c===current?'active':''}" href="${A.path('assets/cv/'+name)}" download>${label}<span>PDF ↓</span></a>`}).join('');d.innerHTML=`<form method="dialog"><button class="mp-modal-close" aria-label="${I.t('close')}">×</button><p class="mp-eyebrow">CV / PDF</p><h2>${I.t('cvTitle')}</h2><p>${I.t('cvText')}</p><div class="kb-cv-grid">${files}</div><button class="mp-btn kb-print" type="button">${I.t('printPortfolio')}</button></form>`;document.body.appendChild(d);d.querySelector('.kb-print').onclick=()=>window.print();document.querySelectorAll('[data-open-cv],#homeCv').forEach(b=>b.onclick=()=>d.showModal())}
  function dock(){if(A.page==='system')return;let x=document.getElementById('kbContactDock');if(!x){x=document.createElement('div');x.id='kbContactDock';x.className='v12-recruiter-dock';document.body.appendChild(x)}const role=roleCode(),name=role?`Kostiantyn_Bryl_CV_${role}_${code()}.pdf`:`Kostiantyn_Bryl_CV_${code()}.pdf`;x.innerHTML=`<a class="primary" href="${A.path('assets/cv/'+name)}" download>CV ↓</a><a href="https://t.me/kostiantynbryl" target="_blank" rel="noreferrer">Telegram</a><a href="mailto:kostiantynbryl@gmail.com">${I.t('email')}</a>`}
  function toast(message){let t=document.getElementById('kbToast');if(!t){t=document.createElement('div');t.id='kbToast';t.className='kb-toast';document.body.appendChild(t)}t.textContent=message;t.classList.add('active');setTimeout(()=>t.classList.remove('active'),3200)}
  function easter(){const brand=document.getElementById('mpBrand');if(!brand||brand.dataset.easter==='1')return;brand.dataset.easter='1';let count=0,timer=0;brand.addEventListener('click',ev=>{if(!ev.target.closest('img'))return;ev.preventDefault();count++;clearTimeout(timer);if(count>=5){count=0;localStorage.setItem('norvexa-system-unlocked','1');toast({en:'System console unlocked.',pl:'Konsola systemowa odblokowana.',ru:'Скрытая консоль разблокирована.',uk:'Приховану консоль розблоковано.',zh:'隐藏控制台已解锁。'}[I.lang]);return}timer=setTimeout(()=>{count=0;location.href=A.path('')},650)})}
  function command(){document.getElementById('kbCommand')?.remove();const d=document.createElement('dialog');d.id='kbCommand';d.className='mp-command';d.innerHTML=`<form method="dialog"><div><span>⌘K</span><input id="kbCommandInput" autocomplete="off" aria-label="${I.t('command')}" placeholder="${I.t('command')}"><button aria-label="${I.t('close')}">Esc</button></div><div class="mp-command-results" id="kbCommandResults"></div></form>`;document.body.appendChild(d);const input=d.querySelector('#kbCommandInput'),results=d.querySelector('#kbCommandResults');let cursor=-1;const items=()=>[[I.t('home'),A.path('')],[I.t('work'),A.path('work/')],[I.t('experience'),A.path('experience/')],[I.t('cases'),A.path('case-studies/')],[I.t('about'),A.path('about/')],[I.t('now'),A.path('now/')],[I.t('ecosystem'),A.path('ecosystem/')],[I.t('contact'),A.path('contact/')],['Telegram','https://t.me/kostiantynbryl'],['GitHub','https://github.com/kostiantynbryl'],['CV','@cv'],[I.t('theme'),'@theme'],...(localStorage.getItem('norvexa-system-unlocked')==='1'?[['System',A.path('system/')]]:[]),...(D.projects||[]).map(x=>[x.name,A.path('work/'+x.id+'/')])];const draw=()=>{const q=input.value.trim().toLowerCase(),list=items().filter(x=>x[0].toLowerCase().includes(q)).slice(0,12);cursor=Math.min(cursor,list.length-1);results.innerHTML=list.map(([label,url],i)=>`<a href="${url}" data-cmd="${url}" class="${i===cursor?'v11-command-active':''}">${A.esc(label)}<span>↗</span></a>`).join('');results.querySelectorAll('a').forEach(a=>a.onclick=ev=>{const u=a.dataset.cmd;if(!u.startsWith('@'))return;ev.preventDefault();if(u==='@cv')document.getElementById('kbCvModal')?.showModal();if(u==='@theme')toggleTheme();d.close()})};input.oninput=()=>{cursor=-1;draw()};input.onkeydown=ev=>{const links=[...results.querySelectorAll('a')];if(ev.key==='ArrowDown'||ev.key==='ArrowUp'){ev.preventDefault();cursor=ev.key==='ArrowDown'?Math.min(cursor+1,links.length-1):Math.max(cursor-1,0);links.forEach((a,i)=>a.classList.toggle('v11-command-active',i===cursor))}if(ev.key==='Enter'&&cursor>=0){ev.preventDefault();links[cursor]?.click()}};draw();const button=document.getElementById('mpCmd');if(button)button.onclick=()=>{d.showModal();setTimeout(()=>input.focus(),20)};if(!window.__kbCommandHotkeyBound){window.__kbCommandHotkeyBound=true;document.addEventListener('keydown',ev=>{if((ev.ctrlKey||ev.metaKey)&&ev.key.toLowerCase()==='k'){ev.preventDefault();const current=document.getElementById('kbCommand'),field=document.getElementById('kbCommandInput');current?.showModal();setTimeout(()=>field?.focus(),20)}})}}
  function bindTheme(){document.getElementById('mpTheme')?.addEventListener('click',toggleTheme)}
  function render(){themeInit();cvModal();dock();command();bindTheme();easter()}
  window.KB_UTILS={render,toggleTheme};
})();
